language: python
matrix:
  include:
    - python: 3.8
      dist: xenial
    - python: 3.7
      dist: xenial
    - python: 3.6
      dist: xenial

notifications:
  email: false

install:
- pip install -r test-requirements.txt
- pip install .

script:
- flake8
- black --check numpy-stubs
- py.test

cache:
  directories:
  - "$HOME/.cache/pip"
