language: python
python:
- 3.6
- 3.7

notifications:
  email: false

install:
- pip install -r test-requirements.txt
- pip install .

script:
- flake8
- black --check numpy-stubs
- py.test

cache:
  directories:
  - "$HOME/.cache/pip"
